# Generated by Django 5.0.3 on 2024-03-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_buildfailure_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='DATE',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submit date'),
        ),
        migrations.AlterField(
            model_name='build',
            name='ERROR_TYPE',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('check-layer', 'check-layer'), ('core', 'Core'), ('bitbake-selftest', 'Bitbake selftest'), ('oe-selftest', 'OE selftest')], default='recipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='buildfailure',
            name='REFERER',
            field=models.CharField(choices=[('NO_REFERER', 'no_referer'), ('OTHER', 'other'), ('NOT_VISITED', 'not_visited')], default='NOT_VISITED', max_length=14),
        ),
    ]
