# Generated by Django 4.2.29 on 2026-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_buildfailure_task_buildfailure_idx_task_lev'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['DATE'], name='idx_date'),
        ),
    ]
